twig:
  default_path: "%kernel.project_dir%/templates"
  form_themes: ["bootstrap_5_layout.html.twig", "Form/custom_theme.html.twig"]

  globals:
    brandName: "%brand_name%"

when@test:
  twig:
    strict_variables: true
