controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

logout:
  path: /logout

login_api:
  path: /api/login
  controller: 'App\Api\Controller\SecurityController::apiLogin'
