name: PR Check
on:
  pull_request:
    types: [opened, edited]

jobs:
  check:
    name: PR Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read PR description
        uses: matyi/pr-changelog-action@v1
        id: pr-changelog
        with:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          destination_branch: master
